version: "3"

services:
  app:
    build: ./app
    restart: always
    expose:
      - 5000
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.wiki.frontend.rule=Host: ${HOST_URL}"
      - "traefik.wiki.port=5000"
      - "traefik.wiki.protocol=http"
    ports:
      - "5000:5000"
    networks:
      - web
    volumes:
      - ./app:/app
      - ./optimization-data:/optimization-data
    depends_on:
      - postgres
    command: ["./wait-for-postgres.sh", "postgres:5432", "--", "python", "app.py"]


  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: optimization

  manager:
    build: ./manager
    restart: always
    volumes:
      - ./manager:/app
      - ./optimization-data:/optimization-data
    command: ["python", "-u", "manager.py"]

  worker:
    build: ./worker
    restart: always
    volumes:
      - ./worker:/app
      - ./optimization-data:/optimization-data
    command: ["python", "-u", "worker.py"]

networks:
  web:
    external: true
  internal:

volumes:
  postgres: