version: "3.7"

services:
  app:
    build: ./app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./optimization-data:/optimization-data
      - ./calculation-data:/calculation-data

  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: optimization

  manager:
    build: ./manager
    restart: always
    volumes:
      - ./manager:/app
      - ./app:/app/opt_app
      - ./optimization-data:/optimization-data
      - ./calculation-data:/calculation-data
    command: ["python", "-u", "manager.py"]

  worker:
    build: ./worker
    restart: always
    volumes:
      - ./worker:/app
      - ./app:/app/opt_app
      - ./optimization-data:/optimization-data
      - ./calculation-data:/calculation-data
    command: ["python", "-u", "worker.py"]

volumes:
  postgres: {}