FROM python:3.6-stretch

MAINTAINER Ralf Junghanns <ralf.junghanns@gmail.com>

# Install numpy
RUN pip install numpy==1.12.0
RUN pip install requests

WORKDIR /app

RUN pip install flopy
RUN pip install scipy
RUN pip install scikit-learn
