import InowasFlopyAdapter

FLOPY_PACKAGENAME_TO_ADAPTER = {
    "Adv": InowasFlopyAdapter.AdvAdapter,
    "Bas": InowasFlopyAdapter.BasAdapter,
    "Btn": InowasFlopyAdapter.BtnAdapter,
    "Chd": InowasFlopyAdapter.ChdAdapter,
    "Dis": InowasFlopyAdapter.DisAdapter,
    "Drn": InowasFlopyAdapter.DrnAdapter,
    "Dsp": InowasFlopyAdapter.DspAdapter,
    "Evt": InowasFlopyAdapter.EvtAdapter,
    "Gcg": InowasFlopyAdapter.GcgAdapter,
    "Ghb": InowasFlopyAdapter.GhbAdapter,
    "Hob": InowasFlopyAdapter.HobAdapter,
    "Lkt": InowasFlopyAdapter.LktAdapter,
    "Lmt": InowasFlopyAdapter.LmtAdapter,
    "Lpf": InowasFlopyAdapter.LpfAdapter,
    "Nwt": InowasFlopyAdapter.NwtAdapter,
    "Oc": InowasFlopyAdapter.OcAdapter,
    "Pcg": InowasFlopyAdapter.PcgAdapter,
    "Phc": InowasFlopyAdapter.PhcAdapter,
    "Rch": InowasFlopyAdapter.RchAdapter,
    "Rct": InowasFlopyAdapter.RctAdapter,
    "Riv": InowasFlopyAdapter.RivAdapter,
    "Sft": InowasFlopyAdapter.SftAdapter,
    "Ssm": InowasFlopyAdapter.SsmAdapter,
    "Swt": InowasFlopyAdapter.SwtAdapter,
    "Tob": InowasFlopyAdapter.TobAdapter,
    "Upw": InowasFlopyAdapter.UpwAdapter,
    "Uzt": InowasFlopyAdapter.UztAdapter,
    "Vdf": InowasFlopyAdapter.VdfAdapter,
    "Vsc": InowasFlopyAdapter.VscAdapter,
    "Well": InowasFlopyAdapter.WelAdapter,
}