import InowasFlopyAdapter

FLOPY_PACKAGENAME_TO_ADAPTER = {
    "Adv": InowasFlopyAdapter.AdvAdapter.AdvAdapter,
    "Bas": InowasFlopyAdapter.BasAdapter.BasAdapter,
    "Btn": InowasFlopyAdapter.BtnAdapter.BtnAdapter,
    "Chd": InowasFlopyAdapter.ChdAdapter.ChdAdapter,
    "Dis": InowasFlopyAdapter.DisAdapter.DisAdapter,
    "Drn": InowasFlopyAdapter.DrnAdapter.DrnAdapter,
    "Dsp": InowasFlopyAdapter.DspAdapter.DspAdapter,
    "Evt": InowasFlopyAdapter.EvtAdapter.EvtAdapter,
    "Gcg": InowasFlopyAdapter.GcgAdapter.GcgAdapter,
    "Ghb": InowasFlopyAdapter.GhbAdapter.GhbAdapter,
    "Hob": InowasFlopyAdapter.HobAdapter.HobAdapter,
    "Lkt": InowasFlopyAdapter.LktAdapter.LktAdapter,
    "Lmt": InowasFlopyAdapter.LmtAdapter.LmtAdapter,
    "Lpf": InowasFlopyAdapter.LpfAdapter.LpfAdapter,
    "Nwt": InowasFlopyAdapter.NwtAdapter.NwtAdapter,
    "Oc": InowasFlopyAdapter.OcAdapter.OcAdapter,
    "Pcg": InowasFlopyAdapter.PcgAdapter.PcgAdapter,
    "Phc": InowasFlopyAdapter.PhcAdapter.PhcAdapter,
    "Rch": InowasFlopyAdapter.RchAdapter.RchAdapter,
    "Rct": InowasFlopyAdapter.RctAdapter.RctAdapter,
    "Riv": InowasFlopyAdapter.RivAdapter.RivAdapter,
    "Sft": InowasFlopyAdapter.SftAdapter.SftAdapter,
    "Ssm": InowasFlopyAdapter.SsmAdapter.SsmAdapter,
    "Swt": InowasFlopyAdapter.SwtAdapter.SwtAdapter,
    "Tob": InowasFlopyAdapter.TobAdapter.TobAdapter,
    "Upw": InowasFlopyAdapter.UpwAdapter.UpwAdapter,
    "Uzt": InowasFlopyAdapter.UztAdapter.UztAdapter,
    "Vdf": InowasFlopyAdapter.VdfAdapter.VdfAdapter,
    "Vsc": InowasFlopyAdapter.VscAdapter.VscAdapter,
    "Wel": InowasFlopyAdapter.WelAdapter.WelAdapter,
}